### ISSUE TITLE
exporting Entity (obj_example) files with textures?

### ISSUE THREAD

**Issue by koalakong** [cbhacks/CrashEdit#123]
Hey there, i have been fiddling with the Crashedit program and came across one of the bomber planes from Warped and some Future level stuff what i would like to export somehow, unfortunately the program made by a user called "warenhuis" that i use to export said models into .ply is very unclear and not really helpful at all according to it's "readme", am i doing something wrong or you just cannot simply extract obj files anymore? whatever the cause might be i have tried everything to almost recieving nothing.

The files i am out for is for example "obj_bomber". (bomber and bomber#2-5).

**Comment by ManDude** [comment]
An entity has nothing to do with the models/animations/graphics related to it, so this is a bit farfetched. If you want to export these (kind of), the graphics data is present in model and animation entries.

**Comment by koalakong** [comment]
But where do i locate the model and animation entries for these type of models? I've seen said Bomber in a video by the same user, but i am as of yet still unsure how or what he did to export that model, i only see T(mumber) based entry folders that do not really contain anything useful from the looks of it.

**Comment by AraHaan** [comment]
Actually each entity has a 5 character name also don't forget that most models, and animations are compressed in a way and is still being cracked to this day. So be patient it is not like the compression can get cracked within the night. That is unless people from Russia decides to chime in and help crack the compression used in Crash Bandicoot 2 and Crash Bandicoot 3 so that way We can export all models / animations.

**Comment by koalakong** [comment]
Actually they have already been cracked (sort of.) allthough said models leave much to desire when it comes to size as seen in image of the plane i need currently. http://i.imgur.com/lNu7foV.png

As for the 5 character name, i am not sure wether you were mistaken by what i wrote about the plane itself or wether said plane actually HAS a 5 character name by entity file. see http://i.imgur.com/rLHyDaO.png

**Comment by ManDude** [comment]
T1 entries are animations and T2 are models, to know an idea of what animation is you could check the appropriate T11 (code/GOOL file) and check the last item and press Z.

And yeah the format has been cracked for a while now.

**Comment by ManDude** [comment]
The size thing you've shown is completely unfixable since that's exactly how the models show up in-game.

**Comment by AraHaan** [comment]
Well then so the compressions on Crash 2 and 3 has been cracked already? guess I am not using the one since I am using the one that actually allows viewing the entire level's scenery as one big scenery. And with it sometimes loading up some models throws an exception that makes it impossible to view any other thing in 3D. AKA the Zones, models, sceneries. In that case I wonder which one actually is coco (Or at least verify the model I think is coco).

**Comment by koalakong** [comment]
The one thing i could actually have any use of is vieweing the textures somehow http://i.imgur.com/f3ftBPQ.png i will ask my cousin who is ironically from Moscow to see if he can somehow crank up an idea for me.

**Comment by ManDude** [comment]
Use [my fork](https://github.com/mandude/CrashEdit/) which allows you to see the animations on the fly.

**Comment by koalakong** [comment]
What do you mean by Fork?

**Comment by ManDude** [comment]
A fork is a "copy" of an original repository where you can make your own changes there and then make a push request to the original repo.

**Comment by koalakong** [comment]
no thanks, this will be for personal use only, he does not like sharing his code/knowledge with others unless known very well by him))

**Comment by ManDude** [comment]
Huh?? It's an open source project so I don't know what you mean by that.
