### ISSUE TITLE
Suggestion: convert project to a newer version of visual studio

### ISSUE THREAD

**Issue by ashelleyPurdue** [cbhacks/CrashEdit#127]
This project is still using visual C# 2005 D:
Please consider converting the project to a newer version, so that way people don't need to search for a 12-year-old download link if they want to contribute

**Comment by ManDude** [comment]
Visual Studio 2015 will automatically convert old project files, this is unnecessary.

**Comment by ashelleyPurdue** [comment]
But then if someone pushes after it gets converted automatically, it will be the converted solution that gets put on the remote.

**Comment by ughman** [comment]
My recommendation is that you base your work off of this fork: https://github.com/mandude/CrashEdit/ . That project appears to be for VS 2013.

The original project was in VS 2005 because the development environment can run on Windows 2000 (which I was using when I first started development) and the compiled software can supposedly run on Windows 98 SE.
