### ISSUE TITLE
Import/Export Entry

### ISSUE THREAD

**Issue by ughman** [cbhacks/CrashEdit#27]
Pretty significant, but also not too difficult, hopefully.

Import needs the rewritten NSD patcher from #23. Export isn't really useful without import.

**Comment by ManDude** [comment]
I found a hacky (and probably very unstable) way to "import" entries by placing them in a chunk in the NSF you want to export the entry from and nothing else in that chunk, opening an hex editor, copying the chunk you want to export and pasting the chunk to the end of the NSF you want the entry to be in (and make sure the CID is correct). I think I'll use this for Hangin' Out for now because it lacks the hard song. You can do this with as many chunks and entries you'd like and you can move the entry out of the imported chunk (and delete it too). Obviously you should patch the NSD after doing this.
