### ISSUE TITLE
Blocked by anti-virus (accidentally)

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#8]
Most advanced anti-virus programs (AVG, etc.) can detect CrashEdit as a virus, but the anti-virus programs don't delete CrashEdit, just block it from using other files (the DLLs), this causes CrashEdit.exe to just open a crash message whenever you try to open it. This can be fixed by adding the CrashEdit folder to the exceptions list (or disabling your anti-virus before starting it up).

**Comment by ughman** [comment]
Which version is this? If it's the one from http://cheek.us.to/CrashEdit.zip then I just uploaded all of the binaries to virustotal here:
- https://www.virustotal.com/en/file/419317d75908890b9b54746cc4a9a3048af9704d69d2fde2c9db70ada00c3ae0/analysis/1421333700/
- https://www.virustotal.com/en/file/228c5834c4ca9a1f8f13829db517b077db88d0cbc4dc2e48c7b9ae4863fb9e08/analysis/1421334250/
- https://www.virustotal.com/en/file/931e38b47b824c316a55b5a54d55650c978ca90dde1daea02299eddd94e719c0/analysis/
- https://www.virustotal.com/en/file/866b16249e2e30f414c788290ccee686df4d104c0edb1d21a345f04e7d274d9b/analysis/

All of these came out clean, with just a single false positive match `BehavesLike.Win32.Backdoor.cm` under `McAfee-GW-Edition`.

I suspect you may actually have a real virus on your system. You were saying before that the EXE "breaks" after a while and needs to be redownloaded. This sounds like it's getting infected after some time on your system and then getting detected as a virus after that, since it really would be a virus at that point.

The MD5 hashes of the files in that zip should be:

```
f0ffe277b4a49a04a7abf87e7b521dc1 *Crash.dll
2f68292e7af3316795c842c0d357b5e6 *CrashEdit.exe
30fea11bc2449b38958547152d9b104c *OpenTK.dll
ae4db35cd83c9def27490851bf25aabe *OpenTK.GLControl.dll
b98d68d079ad79c2f9c1b372e006e57e *Textures.png
```

I did the virustotal uploads and the md5sum checks from the windows system I develop on, but I'll also do these checks from another non-windows system just to be sure.

**Comment by ughman** [comment]
Just checked from linux, same sums and same virustotal results.

**Comment by ManDude** [comment]
Probably just a false-positive, seeing as this is not common.
